### ISSUE TITLE
Add type annotations for mypy?

### ISSUE THREAD

**Issue by benesch** [honeycombio/beeline-python#174] opened 2021-07-17 05:49 UTC
Any interest in adding type annotations for mypy and other Python type checkers? I took a stab at building an external stubs package over at https://github.com/benesch/honeycomb-stubs. I'll do my best to keep it up to date, but it'll more long-term maintainable if the annotations can live inline here. (Plus that means it's possible to ensure the beeline library itself doesn't have any type errors!)

**Comment by pkanal** [comment] 2022-08-19 15:45
Hello,
We are trimming our OSS backlog. We will be closing this issue as it is a low priority for us to fix. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.

**Closed by pkanal** 2022-08-19 15:45 UTC
Labels: type: enhancement

**Comment by benesch** [comment] 2022-08-19 15:58
Hi @pkanal. This issue is important to me. That is why I filed it. I appreciate the expectation setting, and not having the bandwidth to work on this is of course totally fair. But closing this issue just makes it harder for the next person who wants to make this feature request to find the thread.

**Comment by pkanal** [comment] 2022-08-23 18:28
> Hi @pkanal. This issue is important to me. That is why I filed it. I appreciate the expectation setting, and not having the bandwidth to work on this is of course totally fair. But closing this issue just makes it harder for the next person who wants to make this feature request to find the thread.

We really appreciate you filing this issue last year. Even though the issue is closed it will still show up in searches for other folks to find and comment on.

One of the things we do in order to be more transparent in our open source work is do a lot of our work in the open. Keeping issues that we are not going to work on in the near future open is organizational overhead for us as maintainers of this project which is why we feel that closing the issue is the most useful.

We also encourage you to look at OpenTelemetry Python as that is our recommended way of getting data into Honeycomb.

**Comment by benesch** [comment] 2022-08-29 05:43
> We also encourage you to look at OpenTelemetry Python as that is our recommended way of getting data into Honeycomb.

Oh! I didn't realize the beelines were on the deprecation track. That's honestly much more palatable. Thanks for the pointer!
