### ISSUE TITLE
Trace fields and the "app." prefix

### ISSUE THREAD

**Issue by ajvondrak** [honeycombio/beeline-python#113] opened 2020-06-13 22:24 UTC
The Python beeline seems to go to great lengths to prefix trace fields with `app.`, but not context fields. This is proving problematic for my distributed tracing, where my trace-level fields from a Ruby service named like `foo.bar` become `app.foo.bar` on the Python side. Granted, I had to kind of hack around the Ruby beeline to even get trace field without the `app.` prefix, but the same doesn't seem particularly doable in the Python beeline.

This auto-prefixing already bit once with the `app.app.` doubling up in #96. I personally think the whole idea is in need of revisiting across beelines. Why can't the beeline just "do what I say"? The Python beeline already does this for context fields. The `app.` prefix is also not particularly useful to me for distributed tracing; more sensible would be use my different service names as the primary "namespace". Which I could still do with `app.service_name.*`, but the `app.` seems redundant to me.

Those philosophical considerations aside, removing the auto-prefixing of trace fields in the Python beeline would require a major version bump. Perhaps it'd be safer to treat unmarshalled traces specially, avoiding the auto-prefixing? That'd keep the trace-level field names consistent across the distributed trace, at least, which would make for more predictable querying.

**Comment by toshok** [comment] 2020-06-13 23:55
> Why can't the beeline just "do what I say"? The Python beeline already does this for context fields.

good questions, and definitely ones we wrung our hands about.

It's all about ownership of field names/namespaces, really.  versioning of beelines is already a tricky matter, and one thing we've pretty intentionally steered away from so far is "what happens to the version of a beeline when _field names_ change?"  it's a breaking change in terms of instrumentation (existing queries, triggers, boards, etc, can all break), but not an api breaking change.

The problem is greatly exacerbated if there's no separation between beeline-owned fields and user-owned fields, because there's no guarantee that a given user won't already be using a name that we might want to add.

that said - nobody around here is I think particularly in love with `app.`.  maybe there's a better way.

**Comment by ajvondrak** [comment] 2020-06-14 03:40
> it's a breaking change in terms of instrumentation (existing queries, triggers, boards, etc, can all break), but not an api breaking change.

Oh yeah, that's a really good point. Continuity of name changes on the query side would be annoying to handle. Though I guess with something like the auto prefixing there may be an expectation for upgraders to go into their code and manually add the `app.`s. But that's also an imposition on current users.

> The problem is greatly exacerbated if there's no separation between beeline-owned fields and user-owned fields, because there's no guarantee that a given user won't already be using a name that we might want to add.

Makes sense. Guess I'd been thinking about it in the opposite direction: overriding things the beeline is trying to do automatically (e.g., honeycombio/beeline-ruby#66).

> that said - nobody around here is I think particularly in love with `app.`. maybe there's a better way.

Figured y'all had thought about it, but good to know I'm not totally barking up the wrong tree. 🙂

**Comment by mollystamos123** [comment] 2020-09-18 23:32
I have another request to remove the app. prefix in the Python beeline. The request is to consider taking a `prefix=` argument that is set to `app.` by default, but can be overridden.

**Comment by JamieDanielson** [comment] 2021-12-27 20:42
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.

**Closed by JamieDanielson** 2021-12-27 20:42 UTC
