### ISSUE TITLE
beeline.tracer() context manager does not handle exceptions

### ISSUE THREAD

**Issue by hjwp** [honeycombio/beeline-python#172] opened 2021-07-02 13:41 UTC
the docs say that using `with beeline.tracer(...)` should handle exceptions:

>  if an unhandled exception occurs inside a context manager, the event will still get closed, and the exception type and message will get added to the event

https://docs.honeycomb.io/getting-data-in/python/beeline/#using-a-context-manager

in our local testing, we found that this didn't work.  in fact, unhandled exceptions caused the trace to not be sent, at all.

**Comment by MatthewMiele** [comment] 2021-11-11 17:52
I think this might be related to what I have run into over at this bug report https://github.com/honeycombio/beeline-python/issues/164#issuecomment-966485347

**Comment by vreynolds** [comment] 2021-11-17 20:21
Confirmed bug via [greeting service](https://github.com/honeycombio/example-greeting-service/tree/main/python/name-service):
- run name-service alone
- curl the name endpoint
- call to year-service results in an unhanded exception
- unhandled exception results in a missing root span in the trace

It looks like the [_start_response](https://github.com/honeycombio/beeline-python/blob/6a53f4a79dd4a9faffd87180c66385a6b37634a8/beeline/middleware/flask/__init__.py#L46) middleware does not fire when there's an unhandled exception.

**Comment by pkanal** [comment] 2022-08-19 15:44
Hello,
We are trimming our OSS backlog. We will be closing this issue as it is a low priority for us to fix. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.

**Closed by pkanal** 2022-08-19 15:44 UTC
Labels: type: bug
